[build]
  command = "bun run build"
  publish = ".next"
  ignore = "echo 'Skipping Sanity Studio build'"

[build.environment]
  NEXT_PUBLIC_SANITY_PROJECT_ID = "6zhwqxjk"
  NEXT_PUBLIC_SANITY_DATASET = "production"
  NEXT_DISABLE_ESLINT = "1"

# Ignore Sanity Studio folder
[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
